# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5b11a59bbb352f05e4a12744125fb78bc4d6b648e5c7f2fff89fcaceaa748e7ae6dfee80a9a16f717d43de7423223831fccb1b70ae6c487a1294078fbe6b10d

test:
  secret_key_base: 230a5c5a20c10aca4c00d20829b3c14d0f9dc57c654a1e668f67ba98a80078b92d5e2bcce63ece81b52f4c34b21854369cf6d96f7a5c6090e655207e904fdac3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
